fix stuff again

diff --git a/.github/workflows/repo.yml b/.github/workflows/repo.yml
--- a/.github/workflows/repo.yml
+++ b/.github/workflows/repo.yml
@@ -50,7 +50,7 @@ jobs:
           set -euo pipefail
           # config
           REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/repo-host/x86_64"
-          REPO_NAME="custom-repo"
+          REPO_NAME="drags-repo"
           PACKAGE_ROOT="packages"
     
           # setup repo 
@@ -101,7 +101,7 @@ jobs:
             printf "  - %s\n" "${TO_BUILD[@]}"
 
             # Create a JSON array of package directories for the GitHub Actions matrix.
-            json_matrix=$(printf '%s\n' "${TO_BUILD[@]}" | jq -R . | jq -s .)
+            json_matrix=$(printf '%s\n' "${TO_BUILD[@]}" | jq -Rsc .)
             echo "matrix=${json_matrix}" >> "$GITHUB_OUTPUT"
           fi
 
@@ -172,7 +172,7 @@ jobs:
           echo "Fetching existing DB from $REPO_URL"
           
           # Download db.tar.zst and save as .db (repo-add requirement)
-          curl -L -f -o repo/x86_64/drags-repo.db.tar.zst "$REPO_URL/drags-repo.db.tar.zst" || echo "First run or DB missing."
+          curl -L -f -o repo/x86_64/repo.db.tar.zst "$REPO_URL/repo.db.tar.zst" || echo "First run or DB missing."
 
       - name: Download Artifacts
         uses: actions/download-artifact@v4
@@ -186,7 +186,7 @@ jobs:
           cd repo/x86_64
           # Check if files actually exist
           if ls *.pkg.tar.zst 1> /dev/null 2>&1; then
-            repo-add -n -R drags-repo.db.tar.zst *.pkg.tar.zst
+            repo-add -n -R repo.db.tar.zst *.pkg.tar.zst
           fi
       
       - name: Upload binaries to Release
