rename so it's mine

diff --git a/.github/workflows/repo.yml b/.github/workflows/repo.yml
--- a/.github/workflows/repo.yml
+++ b/.github/workflows/repo.yml
@@ -170,7 +170,7 @@ jobs:
           echo "Fetching existing DB from $REPO_URL"
           
           # Download db.tar.zst and save as .db (repo-add requirement)
-          curl -L -f -o repo/x86_64/repo.db.tar.zst "$REPO_URL/repo.db.tar.zst" || echo "First run or DB missing."
+          curl -L -f -o repo/x86_64/drags-repo.db.tar.zst "$REPO_URL/drags-repo.db.tar.zst" || echo "First run or DB missing."
 
       - name: Download Artifacts
         uses: actions/download-artifact@v4
@@ -184,7 +184,7 @@ jobs:
           cd repo/x86_64
           # Check if files actually exist
           if ls *.pkg.tar.zst 1> /dev/null 2>&1; then
-            repo-add -n -R repo.db.tar.zst *.pkg.tar.zst
+            repo-add -n -R drags-repo.db.tar.zst *.pkg.tar.zst
           fi
       
       - name: Upload binaries to Release
